### ISSUE TITLE
Issue with plugin on Katacoda

### ISSUE THREAD

**Issue by allamand** [Orange-OpenSource/cassandra-k8s-operator#77]
When deploying the plugin on Katacoda we have some issues : 

```
kubectl casskop pause
Traceback (most recent call last):
  File "/root/cassandra-k8s-operator/plugins/kubectl-casskop", line 231, in <module>
    Command()
  File "/root/cassandra-k8s-operator/plugins/kubectl-casskop", line 128, in __init__
    print(f"Namespace {get_namespace()}")
  File "/root/cassandra-k8s-operator/plugins/kubectl-casskop", line 81, in get_namespace
    return [p[1] for p in k('config', 'view', '--minify') if "namespace" in p[0]][0]
IndexError: list index out of range
```

to reproduce, execute the plugin on katakoda: https://www.katacoda.com/orange/scenarios/casskop

**Comment by cscetbon** [comment]
Fixed in #78
